services:
  - type: web
    name: frontend
    env: docker
    plan: free
    dockerfilePath: ./frontend/Dockerfile
    envVars:
      - key: NEXT_PUBLIC_BACKEND_URL
        value: http://backend:8080

  - type: web
    name: backend
    env: docker
    plan: free
    dockerfilePath: ./backend/Dockerfile
    envVars:
      - key: DATABASE_URL
        value: postgresql://farm:farm123@postgres:5432/farmdb
      - key: MQTT_URL
        value: mqtt://mqtt:1883
